### ISSUE TITLE
Falha no GetFieldsByType em condição única

### ISSUE THREAD

**Issue by GShalon** [bittencourtthulio/Bind4D#1]
Buenas,

Quando o primeiro campo do banco está marcado como FbIgnoreGet, ao retornar a lista de campos para o Search, inicia a string com "," (virgula), gerando exception. Quando além do guiid adicionei o phone no FbIngnoreGet, duplicou o campo name.

    [FieldJSONBind('guuid'), FbIgnorePost, FbIgnorePut, **FbIgnoreGet]**
    [FieldDataSetBind('guuid',ftString,False,0,'Código')]
    [ComponentBindStyle(COLOR_BACKGROUND, FONT_H6, FONT_COLOR3, FONT_NAME)]
    EditCodigo: TEdit;

Exemplo de retorno para esse método no Zero To Hero:  ',name,phone,occupation,balance,birthdate,lasttransaction,cpf,cnpj'

Com dois campos com ignoreGet: ',name,name,occupation,balance,birthdate,lasttransaction,cpf,cnpj,'

function TBind4D.GetFieldsByType(aType : TTypeBindFormJson) : String;
var
  aAttr : FieldJsonBind;
begin
  for aAttr in RttiUtils.Get<FieldJsonBind>(FForm) do
    **Result := Result + aType.This.GetJsonName(aAttr.Component) + ',';**
  Result := Copy(Result, 1, Length(Result) -1);
end;

Grato!

**Comment by bittencourtthulio** [comment]
Corrigido na versão 1.0.13
