### ISSUE TITLE
Erro DBgrid AdjusteResponsivity

### ISSUE THREAD

**Issue by adelsoncn** [bittencourtthulio/Bind4D#2]
o FComponent.DataSource.DataSet se não for instanciado dar erro,  

na função 
function TBind4DComponentDBGrid.AdjusteResponsivity: iBind4DComponent;

inseri linhas após 

for aAttr in RttiUtils.Get<FieldDataSetBind>(FAttributes.Form) do 
begin

    **if not Assigned(FComponent.DataSource.DataSet) then
       exit;
    if not FComponent.DataSource.DataSet.Active then
       exit;**

**Comment by bittencourtthulio** [comment]
Resolvido na versão 1.0.18
