### ISSUE TITLE
unit Bind4D.Component.DBGrid (Access Violation)

### ISSUE THREAD

**Issue by adelsoncn** [bittencourtthulio/Bind4D#4]
function TBind4DComponentDBGrid.AdjusteResponsivity: iBind4DComponent 

Ao fechar o projeto erro de instancia do FComponent.Columns (Linha 103) ao iniciar o FOR

Inserido verificação antes do FOR

**if not Assigned(FComponent.Columns) then exit;**

**Comment by bittencourtthulio** [comment]
Corrigido na release 1.0.19
